esphome:
  name: $device_name
  comment: "${device_type}"

esp8266:
  board: $board
  framework:
    version: $framework_version

logger:
    level: $logger_level

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH # for ESP8266 LOW/HIGH are mixed up, esphome/issues/issues/1532
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

# web_server:
#   port: 80
#   auth:
#     username: admin
#     password: !secret web_server_password