substitutions:
  device_name: ""
  pretty_name: ""
  device_type: "Goldwin LED Controller"
  icon: ""
  board: "esp01_1m"
  framework_version: "recommended"
  logger_level: INFO

# Common ESP8266 Config
<<: !include .common_esp8266.yaml

# Device Specific Config
light:
  - platform: binary
    name: "${pretty_name}"
    output: light_output
    icon: "${icon}"
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - id: light_output
    platform: gpio
    pin: GPIO12