substitutions:
  device_name: ""
  pretty_name: ""
  device_type: "Merkury MI-WW107-199W"
  icon: ""
  board: "esp01_1m"
  framework_version: "recommended"
  logger_level: INFO

# Common ESP8266 Config
<<: !include .common_esp8266.yaml

# Device Specific Config
binary_sensor:
  - platform: gpio
    id: button1
    pin:
      number: GPIO12
      inverted: true
    on_click:
      - light.toggle: lightid

light:
  - platform: binary
    name: "${pretty_name}"
    output: light_output
    id: lightid
    icon: ${icon}
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: status_led
    id: front_led
    name: "${device_name} Backlight"
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    internal: true
    pin:
      number: GPIO0
      inverted: true

output:
  - id: light_output
    platform: gpio
    pin: GPIO13